server:
  port: 2333

lavalink:
  server:
    password: "youshallnotpass"

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectPlayback: true
    clients:
      - MUSIC

metrics:
  prometheus:
    enabled: false
