server:
  port: 2333

lavalink:
  server:
    password: "youshallnotpass"   # Set your own password
    sources:
      youtube: false             # disable built-in YouTube
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true

plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.16.0"
    repository: "https://maven.lavalink.dev/releases"

metrics:
  prometheus:
    enabled: false
