server:
  port: ${PORT}  # this fixes Render auto-port problem

logging:
  level:
    root: INFO

lavalink:
  server:
    password: "Euonia"   # change this and also use it in your bot
    sources:
      youtube: true
      youtubeMusic: true
      spotify: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false

    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    gc-warnings: true

plugins:
  # YouTube plugin (recommended)
  - dependency: "com.lavalink-devs:youtubesource:1.10.0"
    repository: "https://maven.lavalink.dev/releases"
