server:
  address: 0.0.0.0           # Listen on all interfaces
  port: ${PORT}              # Render provides this automatically

lavalink:
  server:
    password: "Euonia"  # Must match your bot
    sources:
      youtube: true
      youtubeMusic: true
      soundcloud: true
      http: true
      local: false
    bufferDurationMs: 4000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    serverRegion: "us_central"         # adjust as needed


plugins:
  # YouTube plugin (recommended)
  - dependency: "com.lavalink-devs:youtubesource:1.10.0"
    repository: "https://maven.lavalink.dev/releases"
