server:
  port: ${PORT}

lavalink:
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
    youtubeSearchEnabled: true

logging:
  file: logs/lavalink.log
  level:
    root: INFO
